spring:

  # H2 DATABASE
  h2:
    console:
      enabled: true
      path=: '/h2-console'
  datasource:
    url: 'jdbc:h2:mem:articles_DB'
    driverClassName: 'org.h2.Driver'
    username: 'admin'
    password: ''

  # JPA MODE
  jpa:
    show-sql: true

  # turn off display banner
  main:
    banner-mode: off