trigger:
  - develop

pr:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - script: 'gradle clean build'
        displayName: 'Build with Gradle'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/build/libs'
          artifactName: 'drop'
          publishLocation: 'Container'
