trigger:
  - develop

pr:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: |
              echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
            displayName: 'Set JAVA_HOME variable'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(Build.SourcesDirectory)/build/libs'
              artifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
            displayName: 'Set JAVA_HOME variable'
